name:                docker-secondary-agent
version:             0.1.0.0
github:              "githubuser/docker-secondary-agent"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/docker-secondary-agent#readme>

dependencies:
- base >= 4.7 && < 5
- aeson == 2.1.2.1
- load-env == 0.2.1.0
- text ^>= 2
- bytestring == 0.12.3
- amqp == 0.22.1
- docker == 0.7.0.1
- command == 0.1.1
- optparse-applicative == 0.17.1.0
- network == 3.1.4.0
- uuid == 1.3.15
- directory == 1.3.7.1
- containers == 0.6.7
- unordered-containers == 0.2.19.1
- conduit == 1.3.4.2
- exceptions == 0.10.7

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  docker-secondary-agent-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - docker-secondary-agent

tests:
  docker-secondary-agent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - docker-secondary-agent
