name:                docker-master-server
version:             0.1.0.0
github:              "githubuser/docker-master-server"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mrtstg/ln2/docker-master-server#readme>

dependencies:
- base >= 4.7 && < 5
- aeson == 2.1.2.1
- yaml == 0.11.11.2
- yesod-core == 1.6.24.5
- optparse-applicative == 0.17.1.0
- load-env == 0.2.1.0
- text ^>= 2
- directory == 1.3.7.1
- filepath == 1.4.2.2
- http-types == 0.12.3
- bytestring == 0.11.5.2
- amqp == 0.22.1
- monad-logger == 0.3.40
- network == 3.1.4.0
- http-types == 0.12.3
- yesod-persistent == 1.6.0.8
- persistent ^>= 2.14
- persistent-postgresql == 2.13.6.1
- resource-pool == 0.4.0.0
- uuid == 1.3.15
- containers == 0.6.7

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  docker-master-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - docker-master-server

tests:
  docker-master-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - docker-master-server
