version: '3'
services:
  dev-db:
    profiles: ['dev']
    image: postgres:16.1-alpine
    container_name: ln2-dev-db
    hostname: db
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  dev-redis:
    profiles: ['dev']
    image: redis:7.2.1-alpine
    container_name: ln2-dev-redis
    hostname: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  dev-rabbitmq:
    profiles: ['dev']
    image: rabbitmq:3.13-rc-management-alpine
    container_name: ln2-dev-rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    env_file:
      - ../.env
  dev-nginx:
    profiles: ['dev']
    image: nginx:stable-alpine
    container_name: ln2-dev-nginx
    hostname: nginx
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/dev.conf:/etc/nginx/conf.d/site.conf:ro
      - ../static/:/static:ro
  dev-pgadmin:
    profiles: ['dev']
    image: dpage/pgadmin4:8.6
    container_name: ln2-dev-pgadmin
    restart: unless-stopped
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: P@ssword
    ports:
      - 8080:80
    volumes:
      - ../pgadmin:/var/lib/pgadmin
