version: '3'
services:
  prod-db:
    profiles: ['prod']
    image: postgres:16.1-alpine
    container_name: ln2-prod-db
    hostname: db
    env_file:
      - ../docker.env
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  dev-db:
    profiles: ['dev']
    image: postgres:16.1-alpine
    container_name: ln2-dev-db
    hostname: db
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  prod-redis:
    profiles: ['prod']
    image: redis:7.2.1-alpine
    container_name: ln2-prod-redis
    hostname: redis
    restart: unless-stopped
  dev-redis:
    profiles: ['dev']
    image: redis:7.2.1-alpine
    container_name: ln2-dev-redis
    hostname: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  prod-rabbitmq:
    profiles: ['prod']
    image: rabbitmq:3.13-rc
    container_name: ln2-prod-rabbitmq
    hostname: rmq
    restart: unless-stopped
    env_file:
      - ../docker.env
  dev-rabbitmq:
    profiles: ['dev']
    image: rabbitmq:3.13-rc-management-alpine
    container_name: ln2-dev-rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    env_file:
      - ../.env
  dev-websocket:
    image: ln2-websockify
    container_name: ln2-dev-websockify
    hostname: websockify
    ports:
      - 6080:6080
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ./websockify/entrypoint.sh:/entrypoint.sh:ro
      - ./websockify/tokens.cfg:/tokens.cfg.template:ro
  dev-nginx:
    profiles: ['dev']
    image: nginx:stable-alpine
    container_name: ln2-dev-nginx
    hostname: nginx
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/dev.conf:/etc/nginx/conf.d/site.conf:ro
      - ../static/:/static:ro
    depends_on:
      - dev-websocket
  dev-pgadmin:
    profiles: ['dev']
    image: dpage/pgadmin4:8.6
    container_name: ln2-dev-pgadmin
    restart: unless-stopped
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: P@ssword
    ports:
      - 8080:80
    volumes:
      - ../pgadmin:/var/lib/pgadmin
  prod-md-api:
    profiles: ['prod']
    image: ln2-md-api
    container_name: ln2-prod-md-api
    restart: unless-stopped
    env_file:
      - ../docker.env
    hostname: md-api
  prod-db-api:
    profiles: ['prod']
    image: ln2-db-api
    container_name: ln2-prod-db-api
    restart: unless-stopped
    env_file:
      - ../docker.env
    hostname: db-api
  prod-auth:
    profiles: ['prod']
    image: ln2-auth
    container_name: ln2-prod-auth
    restart: unless-stopped
    env_file:
      - ../docker.env
    hostname: auth
    depends_on:
      - prod-db
      - prod-redis
  prod-main-site:
    profiles: ['prod']
    image: ln2-main-site
    container_name: ln2-prod-main-site
    restart: unless-stopped
    env_file:
      - ../docker.env
    hostname: main
    depends_on:
      - prod-db
      - prod-redis
      - prod-rabbitmq
      - prod-auth
      - prod-md-api
      - prod-db-api
  prod-master:
    profiles: ['prod']
    image: ln2-master
    container_name: ln2-prod-master
    restart: unless-stopped
    env_file:
      - ../docker.env
    hostname: master
    depends_on:
      - prod-db
      - prod-rabbitmq
    volumes:
      - ../docker-master-server/stands:/usr/src/app/stands
  prod-agent:
    profiles: ['prod']
    image: ln2-agent
    container_name: ln2-prod-agent
    restart: unless-stopped
    user: root
    privileged: true
    env_file:
      - ../docker.env
    hostname: agent
    depends_on:
      - prod-rabbitmq
    volumes:
      - ${DOCKER_SOCKET}:/run/docker.sock
    deploy:
      resources:
        reservations:
          cpus: '0.050'
        limits:
          cpus: '0.500'
  prod-nginx:
    profiles: ['prod']
    image: nginx:stable-alpine
    container_name: ln2-prod-nginx
    hostname: nginx
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/prod.conf:/etc/nginx/conf.d/site.conf:ro
      - ../static:/static:ro
    depends_on:
      - prod-main-site
