name:                md-render-api
version:             0.1.0.0
github:              "githubuser/md-render-api"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/md-render-api#readme>

dependencies:
- base >= 4.7 && < 5
- aeson == 2.1.2.1
- yesod-core == 1.6.24.5
- optparse-applicative == 0.17.1.0
- load-env == 0.2.1.0
- text ^>= 2
- http-types == 0.12.3
- http-conduit == 2.3.8.1
- transformers == 0.5.6.2
- wai-cors == 0.2.7
- warp == 3.3.25
- attoparsec == 0.14.4
- bytestring == 0.11.5.2
- blaze-html == 0.9.1.2
- MissingH == 1.6.0.1
- directory == 1.3.7.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  md-render-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - md-render-api

tests:
  md-render-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - md-render-api
